-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE7mfnDzVBesDjLJl
DdyBMuvzErGlE/58GG6pffdZOIWgCgYIKoZIzj0DAQehRANCAATm+LirgswSUh3C
5Kpy0AmZU+Iozov9LMULuv2veaubk4LNJYqjwUCVoLt+VJwgamUJAiWElCyZKc+C
2DpU8ZZY
-----END PRIVATE KEY-----